### ISSUE TITLE
refresh loaded file in iOS

### ISSUE THREAD

**Issue by reflectored** [sodenn/2do-txt#1115]
Hi @sodenn I love your iOS app! I sync the .txt file between my computer(s) and the iPhone using syncthing, and I need to manually reload the file on iOS to see the updates - is it possible that you implement a refresh on the file? Thanks!

**Comment by sodenn** [comment]
Hi @reflectored, thank you for your feedback. I'm currently focused on a major refactoring of the app, moving towards a web-based approach using Web APIs to simplify development across platforms. As part of this shift, I'm planning to focus less on native platform apps, including iOS.
For file syncing on iOS, I’ll be exploring new solutions in the future, as the old mechanism stores secrets (like Dropbox tokens or WebDAV passwords) in the iOS Keychain, which isn’t possible in a purely web-based solution.
However, as soon as I start working on file sync, I will consider a refresh function.
