### ISSUE TITLE
File is not updated when using Dropbox integrated into Files

### ISSUE THREAD

**Issue by acyment** [sodenn/2do-txt#215]
I'm using a todo.txt file that corresponds to a Dropbox folder within Files in iOS. Changes seem to be saved somewhere, because they persist when I go back to the app (they persist even if I close and reopen the app). Changes do not seem to be saved to the actual file though. If I check the file in my Dropbox account (even when using the Dropbox app in the same phone) I don't see any changes made to the file.

This bug renders the app unusable in my case, because I need the file to be in sync with at least one more device (a laptop running Linux). 

Thanks!

**Comment by acyment** [comment]
I just did the check the other way (changed and saved file on desktop, synced to Dropbox and 2do-txt on the phone does not update)

**Comment by sodenn** [comment]
Hi @acyment,
the App uses the [@capacitor/filesystem](https://capacitorjs.com/docs/apis/filesystem) Plugin for working with files. Unfortunately, the file access on iOS is very limited. At the moment the app can only write to its own sandbox storage systems. I'm already thinking about how to improve it. Perhaps by syncing the todo.txt in the app’s documents directory with a cloud storage provider (Dropbox, Google Drive).

**Comment by TonyBarganski** [comment]
Have the same problem. 
I’ve been using SwiftoDo for a couple of years now but stumbled upon your app and much prefer the way you show the filters @sodenn 

But it won’t update with Dropbox.

**Comment by sodenn** [comment]
FYI, I've started integrating a Dropbox sync #234
