### ISSUE TITLE
IOS: App doesnt save the file

### ISSUE THREAD

**Issue by tomasdurham** [sodenn/2do-txt#232]
The tasks written in the app is not saved in the phone/icloud or in other folders. when I open a file in the folder and add tasks, the new task is not visible in the .txt file.

**Comment by tomasdurham** [comment]
Hi @sodenn thanks here for the answer too. I am searching for an application that makes it possible to sync with my todo.txt file, which is shared through smb. I am using a lot of different operating systems. When the file is just saved in the isolated app directory, then the app is for my preferences not really usable. It would be nice to have the sync feature across the devices with the "folder" app from iOS, where I have access to my files through smb. 
I like the simple design from your app and would like to use it.

**Comment by mshuflin** [comment]
@sodenn I am in the same situation as @tomasdurham, the ability to have it automatically sync to a folder would be what makes the app usable. I use Syncthing (Mobius Sync on iOS) for all my devices, so I would like to be able to sync a folder with the .txt files.

**Comment by loganrv** [comment]
I agree, I prefer not using Dropbox but want cross-device sync via Files.

**Comment by sodenn** [comment]
Unfortunately, the file access on iOS is very limited. There are apps that use a so-called "File Provider" to enable access to the file system. However, these apps are usually native apps, and I doubt if this is possible in Capacitor/Cordova apps.
I will check what improvement I can make. Any contribution would be welcome!

**Comment by mshuflin** [comment]
I use https://github.com/MobiusSync/MobiusSync on the iPad, since it works with Syncthing on all my other devices. I use that for syncing syncing todo.txt in android, mac, linux, etc

**Comment by mshuflin** [comment]
still an issue

**Comment by loganrv** [comment]
If this could sync to files or WebDAV or something, I would start using this app.

**Comment by apastuszak** [comment]
WebDAV would be a great choice, because that is what Nextcloud supports.

**Comment by mshuflin** [comment]
Still an issue

**Comment by sodenn** [comment]
> If this could sync to files or WebDAV, I would start using this app.

I started working on #649

**Comment by loganrv** [comment]
> > If this could sync to files or WebDAV, I would start using this app.
> 
> I started working on #649

That’s awesome!

**Comment by mshuflin** [comment]
Still an issue

**Comment by mshuflin** [comment]
still an issue

**Comment by mshuflin** [comment]
Still an issue
