### ISSUE TITLE
IOS: Button share is not working

### ISSUE THREAD

**Issue by tomasdurham** [sodenn/2do-txt#233]
The share-button is not working aswell. Has no function in it.

**Comment by sodenn** [comment]
Hi @tomasdurham,
thanks for the information. Can you please tell me which device and iOS version you are using? 
I have just successfully tested the share function on my iPhone XS with iOS 15.2.1.

**Comment by tomasdurham** [comment]
Hi @sodenn Thanks for the answer. I am using Iphone 7 and had a one month older version. So I updated to the latest 15.3.1 and now the share button is working!

**Comment by sodenn** [comment]
Nice, thank you for response.
