### ISSUE TITLE
Dropbox API User Limit Reached

### ISSUE THREAD

**Issue by TonyBarganski** [sodenn/2do-txt#256]
Error connecting app:
This app has reached its user limit.
Contact the app developer and ask them to use the Developer API App Console to increase theor app’s user limit.

See attached photo:
![6038971B-EA6B-4B5A-ADE0-FBB50D7CE473](https://user-images.githubusercontent.com/46673133/158567687-7f29bf46-310e-4dff-b1fa-4f63566ad83f.png)

**Comment by sodenn** [comment]
Thanks for sharing it. I just applied for production status. I hope that the account limit will then be removed.

**Comment by TonyBarganski** [comment]
Thanks @sodenn!

I've been checking it each day but still the same problem at the moment1

**Comment by sodenn** [comment]
I just checked the status but the review from Dropbox is still pending. I'll keep you up to date with this process.

**Comment by sodenn** [comment]
Good news, Dropbox has upgraded the app to production status. The account limit should now be removed.
