### ISSUE TITLE
Feature Request: macOS version

### ISSUE THREAD

**Issue by TonyBarganski** [sodenn/2do-txt#286]
Hi @sodenn 

Now that the Dropbox synch is working I am happy to use the app on my phone and wonder when is the Desktop macOS version coming out?

**Comment by sodenn** [comment]
Thanks Tony, I have it on my list. Technically, the Dropbox integration already works for the desktop app. But before I enable this feature, the tokens have to be stored securely via the system keychain just like in the iOS app.
