### ISSUE TITLE
Filters & Keyboard Shortcuts

### ISSUE THREAD

**Issue by TonyBarganski** [sodenn/2do-txt#293]
As I've mentioned before, I love the 'ballon' filter design which allows for 'fast' & 'easy' filtering but the filters currently do not work they way I would expect.

#### 1. Narrow down tasks to match **only** the filter criteria selected
So, if I have a task named, "(A) Get a copy of the deeds set to Steven +houseSale @call due:2022-03-31" I would that if I select filters:

`@call +houseSale`

I will see **only** this task but I see all tasks which have the context @call. Additionally, when I further narrow down the filter criteria and select Priority (A) I see all my priority (A) tasks now but I would like to see only those that have `@call +houseSale`.

#### 2. Paste a task into the *Create Task -> Description* box
This doesn't work currently and would be a nice to have.

#### 3. Task Creation 
Three things here:
a) Task field selection. For instance, to select Priority, one needs to tab to it, then dropdown, up/down-arrow to select priority A,B,C,D then [Enter]. It would be much quicker to: tab, type A (a list of current priorities within the todo.txt appear with the typed selected), tab to select it, [Enter]

b)  "Creation Date" is the 3rd selection box one needs to tab too. Does this even need to be here? Its pre-filled to today's date so how about having a check box in the settings stating whether to automatically append creation dates to new tasks or not?

c) Due Date: It would be great to be able to simply type, "today", "tomorrow", "day after tomorrow", "2 days from now", "1 week" or "1w" and have the select box fill in the date. 

#### 4. Keyboard Shortcuts
Last but not least: Since my personal aim is to use the keyboard for most of my commands and interactions for its speed and flow, and use the mouse for filter selection and such, keyboard shortcuts are very important.

There is no help menu yet but most of the shortcut keys were easy for me to discover, like pressing [Enter] saves the task, [Spacebar] brings up the filter menu (very nice but doesn't always work), as does pressing [m] and [Esc] to hide it.

What would be very handy is to have a shortcut key which CLEARS the Filters, perhaps something like, [Del] & [Ctr-l]  for cLear screen which us terminal users are some familiar with.

**Comment by sodenn** [comment]
Hi Tony,
many good points, thank you.
I've created some separate issues for better overview:

- #297 
- #298 
- #299 
- #300 

Question to the 2nd point:
What exactly doesn't work about copy & pasting the task text? Can you give an example text?

**Comment by sodenn** [comment]
FYI, in the latest release I fixed two issues related to copy & paste (#309, #314). Please check it again.

**Comment by TonyBarganski** [comment]
Hi @sodenn 
At your request, I've evaluated the changes made and have some further suggestions.
- Regarding #297 

[todotxt.org](http://todotxt.org) rightly defines the **todo.txt format rules** as having **only one** Priority, one "+project" and one "@context" while allowing for **multiple tags** extending functionality and filtering.

To that end, I would suggest that once a Priority/Project/Context is selected on the 'bubble filter' screen, no further selections on those criteria should be allowed, i.e. those options should appear greyed out until a filter option is deselected once more.

For "Tags:" I think there is where one should be allowed to select multiple ANDed tags.

**Comment by TonyBarganski** [comment]
- Regarding #300

[Edit Task] shows the old edit menu with the "Creation Date" & "Completion Date" for tasks which are NOT completed which is a little confusing.

**Comment by TonyBarganski** [comment]
- Regarding #298 
This is a great improvement on the general flow and speed of task creation with paste working. 
I have two more suggestions to make it really smooth:

The objective here for me personally is:
1. Speed of task creation
2. I should not "need" to touch my mouse at all to create a perfectly formed todo.txt task (which gives me great speed)

To that end, please review my suggestions below:

[Due Date] format
1. mm/dd/yyyy is the default. This should be read from the users Regional Settings. 
For instance, in the UK, the format is dd/mm/yyyy

2. I should be able to type, "today", "tomorrow", "on Wednesday", "in 2 days", etc. 
macOS Calendar's Natural Language has a nice list and you might be able to use its API for this, don't know.

[Cancel] [Save] - Tab Selection
1. Tab Selection does not work for these two fields on the "Create Task" screen.

I'm tabbing down the form fields on the "Create Task" screen and all 3 boxes work as expected until I get to [Cancel] [Save] which do not highlight on tab select. I try another tab thinking it might be on [Cancel] but just not visible so I tag again and then press Enter and my task goes into oblivion :( 

a) Suggest enabling 'tab selection'
b) Suggest reversing the order and putting the [Save] option before [Cancel]
[X] [Cancel] [Save]
[V] [Save] [Cancel]

This way, saving my important task is just one Tab away from Due Date.
Outcome is that one can tab from Due Date to [Save] and press [Return] to save the task.

**Comment by sodenn** [comment]
> [todotxt.org](http://todotxt.org) rightly defines the **todo.txt format rules** as having **only one** "Priority", one "+project" and one "@context" while allowing for **multiple tags** extending functionality and filtering.
> 
@TonyBarganski Are you sure? I thought you could add multiple contexts and projects per task.
[Rule 3](https://github.com/todotxt/todo.txt#rule-3-contexts-and-projects-may-appear-anywhere-in-the-line-after-priorityprepended-date) - "task may have zero, one, or more than one projects and contexts included in it."

**Comment by sodenn** [comment]
> * Regarding [Hide creation date when creating a new task #300](https://github.com/sodenn/2do-txt/issues/300)
>
> [Edit Task] shows the old edit menu with the "Creation Date" & "Completion Date" for tasks which are NOT completed which is a little confusing.

Good point. When editing an incomplete task, the input field for the completion date should be hidden because it is not needed in this state.

**Comment by sodenn** [comment]
> * Regarding [Better keyboard support for task priority selection #298](https://github.com/sodenn/2do-txt/issues/298)
>   This is a great improvement on the general flow and speed of task creation with paste working.
>   I have two more suggestions to make it really smooth:
> 
> The objective here for me personally is:
> 
> 1. Speed of task creation
> 2. I should not "need" to touch my mouse at all to create a perfectly formed todo.txt task (which gives me great speed)
> 
> To that end, please review my suggestions below:
> 
> [Due Date] format
> 
> 1. mm/dd/yyyy is the default. This should be read from the users Regional Settings.
>    For instance, in the UK, the format is dd/mm/yyyy
> 2. I should be able to type, "today", "tomorrow", "on Wednesday", "in 2 days", etc.
>    macOS Calendar's Natural Language has a nice list and you might be able to use its API for this, don't know.
> 
> [Cancel] [Save] - Tab Selection
> 
> 1. Tab Selection does not work for these two fields on the "Create Task" screen.
> 
> I'm tabbing down the form fields on the "Create Task" screen and all 3 boxes work as expected until I get to [Cancel] [Save] which do not highlight on tab select. I try another tab thinking it might be on [Cancel] but just not visible. I then press [Enter] on my keyboard and my task goes into oblivion :(
> 
> a) Suggest enabling 'tab selection' b) Suggest reversing the order and putting the [Save] option before [Cancel] [X] [Cancel] [Save] [V] [Save] [Cancel]
> 
> This way, saving my important task is just one Tab away from Due Date. Outcome is that one can tab from Due Date to the [Save] button and then press [Enter] on the keyboard to save a task.

There are two improvements to this in the next release:
- Buttons can be focused with Tab key and are highlighted
- The cancel button in the task dialog is not focusable via keyboard (Tab key) to avoid accidentally canceling it

The date picker also benefits from this, since the small calendar icon can now be focused by tab. This makes it easy to open the calendar using the keyboard.

**Comment by TonyBarganski** [comment]
> > [todotxt.org](http://todotxt.org) rightly defines the **todo.txt format rules** as having **only one** "Priority", one "+project" and one "@context" while allowing for **multiple tags** extending functionality and filtering.
> 
> @TonyBarganski Are you sure? I thought you could add multiple contexts and projects per task. [Rule 3](https://github.com/todotxt/todo.txt#rule-3-contexts-and-projects-may-appear-anywhere-in-the-line-after-priorityprepended-date) - "task may have zero, one, or more than one projects and contexts included in it."

@sodenn I stand corrected on this point and thinking it through some more, it does actually makes sense to support multiple Project and Context per task.

**Comment by TonyBarganski** [comment]
> Hi @sodenn At your request, I've evaluated the changes made and have some further suggestions.
> 
> * Regarding [Multiple filter conditions should be "ANDed" together #297](https://github.com/sodenn/2do-txt/issues/297)
> 
> Firstly, the ANDing of filters now works much, much better and I have a further suggestion:
> 
> [todotxt.org](http://todotxt.org) rightly defines the **todo.txt format rules** as having **only one** "Priority", one "+project" and one "@context" while allowing for **multiple tags** extending functionality and filtering.
> 
> To that end, I would suggest that once a Priority/Project/Context is selected on the 'bubble filter' screen, no further selections on those criteria should be allowed, i.e. those options should appear greyed out until a filter option is deselected once more.
> 
> For "Tags:" I think here is where one _should_ be allowed to select multiple ANDed tags.

@sodenn I stand corrected on this point and thinking it through some more, it does actually makes sense to support multiple Project and Context per task.
