### ISSUE TITLE
Add Support for archiving completed tasks to done.txt 

### ISSUE THREAD

**Issue by TonyBarganski** [sodenn/2do-txt#330]
The popular [Todo.txt CLI](https://github.com/todotxt/todo.txt-cli/wiki/User-Documentation) tools listed on [todotxt.org](http://todotxt.org) support archiving completed tasks to a file named `done.txt`.

It is great to see one's progress each day crossing out a task on a list. It's one of the most fundamental parts of a task list. However, once those tasks are older than a day, and we get a build up of strike-through tasks, it gets visually messy.

Often, one will want or need to revisit a task after it has been completed for reference, to re-instate a task or even to have a task on a recurring schedule. Its therefore important to keep the old tasks someplace. `done.txt` accomplishes this.

**Comment by sodenn** [comment]
Thanks, Tony. I have it on my list. Because **2do.txt** supports working with multiple files, the `done.txt` should then have a prefix. For example:
`todo.txt` => `done.txt`
`todo1.txt` => `todo1_done.txt`
