### ISSUE TITLE
Filter Options [Checkbox]

### ISSUE THREAD

**Issue by TonyBarganski** [sodenn/2do-txt#331]
### Filter Options
While the bubble filter screen looks amazing, I've found filter options themselves lack the functionality I've been used to when using my own Bash script filtering from the CLI and the filter options within the popular [Swiftodo Desktop](https://swiftodoapp.com/desktop/) app.

I've found the filter options on the [Swiftodo Desktop](https://swiftodoapp.com/desktop/) app great but not intuitively named or well documented. Using these as a basis, I've renamed the filter functions and re-written the descriptions a little here with a feature request to have a toggle section on the filters page like so:

```
[X] Focus mode
[ ] Strick mode
[ ] Any mode
```

These would correspond to the following:

#### [Focus mode] 
Focus is meant to filter the list down to tasks for multiple projects which have contexts and/or priorities in common.

For example, use the "Focus" filter to return tasks from the +work project or the +home project, with context @phone or @office, and priority (A) or (B).

#### [Strict mode]
All filter conditions must be strictly met. Filter conditions are considered together (ANDed).
For example, use the "Strict" filter to return only those tasks with project +work and context @phone and priority (A).

#### [Any mode] (Any)
Include tasks with any of the filter conditions selected. 
This filter mode will return tasks that match any of the projects, contexts, or priorities selected.

For example, use the "Any" filter to return all tasks for the +work project and the +home project, and all tasks with the @phone context, and all tasks with priority (A) or (B).

**Comment by TonyBarganski** [comment]
Extending on this, I would suggest a **Due date** filter. Something like:

[X] Due today
[  ] Past due
[  ] Future due

**Comment by sodenn** [comment]
Thanks Tony. I already planned to provide an option to switch between AND filter and OR filter, but I like your suggestion too. You can test the current status of this feature on [sodenn.github.io/2do-txt/](https://sodenn.github.io/2do-txt/). 
I named the filter types based on your suggestion. But I'm not sure if I understood the "Focus" option correctly.
Feel free to check it out and leave your feedback.

**Comment by TonyBarganski** [comment]
@sodenn  To be honest, I can't see the difference between the (Any) filter and the (Focus) or (Mix filter as  [Swiftodo Desktop](https://swiftodoapp.com/desktop/) documents it.

Having and AND and OR filter should be good enough for starters. I've never used the (Any) filter and mostly use the (Mix/Focus) filters personally.

**Comment by TonyBarganski** [comment]
@sodenn I see you've committed these changes to the repo. Just wondering what your release cycle is and when you are planning to build the binaries for this feature? :)
