### ISSUE TITLE
Add support for Nextcloud/WebDAV

### ISSUE THREAD

**Issue by apastuszak** [sodenn/2do-txt#649]
I'm trying to find a todo.txt client for iOS that edit/update a file on a Nextcloud server. Nextcloud supports WebDAV.

Dropbox is just too expensive. I'm not spending $10/month to sync one small todo.txt file.

**Comment by whnr** [comment]
If it’s just that: there’s still the [free Basic account](https://www.dropbox.com/basic).

but I agree! WebDAV would be awesome.

**Comment by apastuszak** [comment]
The free basic account is limited to 2 devices.

**Comment by whnr** [comment]
API access does not seem to count against the device count. I used dropbox for the first time in years yesterday and added 2 devices that both don’t show up:

- 2do-txt
- [maestral.app](https://maestral.app/) Open-source Dropbox client for macOS and Linux

With your comment I saw that I have 9 of 3 allowed devices registered 🙈.

**Comment by apastuszak** [comment]
I can give it a try. I still need 3 PCs synced, so Dropbox may not work for me.

**Comment by sodenn** [comment]
FYI, I started working on a WebDAV integration.

**Comment by sodenn** [comment]
The beta version (Desktop) is ready for testing: https://github.com/sodenn/2do-txt/releases/tag/v1.16.0-webdav.1. 
The iOS beta version will be available soon.
