### ISSUE TITLE
Can't open file synced in Dropbox (problem with folder name)

### ISSUE THREAD

**Issue by acyment** [sodenn/2do-txt#674]
The iOS app saves its file inside a folder named "2do.txt" when using Dropbox. When I try to open the same file in a Mac, I can't navigate to the file because the app thinks the folder named "2do.txt" is an actual text file. 

Screen recording is attached.

https://user-images.githubusercontent.com/1872616/192396997-91a02db1-bf15-4c24-a22a-231c7ce4ee0f.mov

**Comment by acyment** [comment]
Perhaps it'd just be easier to change the name of the folder, as it actually becomes problematic as it is for other todo.txt clients (see https://github.com/ransome1/sleek/issues/413)

**Comment by sodenn** [comment]
Thanks for the report @acyment. I will fix it in the next release. Until then, you can use the drag and drop function to open the file.
