### ISSUE TITLE
Sync interval

### ISSUE THREAD

**Issue by apastuszak** [sodenn/2do-txt#730]
Is there some way to force a sync?

I have 2do.txt on my iPhone, iPad and am using todo.sh on my Mac.

When I make a change on my Mac, the app on my iPad and iPhone doesn't pick up the change unless I quit the app and relaunch it.

Is there a way to force a sync? Can we add a UI button to do a sync?

**Comment by sodenn** [comment]
Good point. Currently the app starts a sync after opening and after a file save. It would probably be a good idea to additionally start a synch as soon as the app becomes active.

**Comment by apastuszak** [comment]
What about a manual sync option also?

**Comment by sodenn** [comment]
> What about a manual sync option also?

Yes, we can provide that additionally.

**Comment by apastuszak** [comment]
Is this going to be added to the iOS release also?
