### ISSUE TITLE
Error connecting to cloud storage: Failed to parse response Created as JSON

### ISSUE THREAD

**Issue by andreatitolo** [sodenn/2do-txt#754]
Hi! sorry to bother with another issue. When first starting the app, it connects correctly with the cloud storage. However, if I edit something, I will get a connection error.

```
Error connecting to cloud storage:
Failed to parse response Created as JSON: SyntaxError: JSON Parse error: Unexpected identifier "Created":
try setting the responseType option to 'ResponseType. Text' or 'ResponseType. Binary if the API does not return a JSON response.
```

After this error started to show up, some of my changes are not saved immediately, but it happens somewhat randomly: e.g. if I create a new task sometimes it is not saved, and I need to create it again; or I can create the task but the priority and other fields (Projects/Contexts) are not saved, and I need to edit the task to add them again.
Not sure if these two are related, but thank you again for all your work! :)

Edit: reading through the error, it seems the "Created" field is causing some issues?

**Comment by andreatitolo** [comment]
Hi! sure, I am using [Koofr](https://koofr.eu/help/koofr_with_webdav/how-do-i-connect-a-service-to-koofr-through-webdav/) as webdav server (the free plan allow for using webdav). 

I just tested the prerelease and unfortunately I had the same error, always after the first action after opening the app. Deleting the test task also took a couple of tries. I don't know if it's worth mentioning that I am on a very, very slow connection during these days, not sure if it can have any meaningful impact tough.
Thank you again! :)

**Comment by sodenn** [comment]
I was able to reproduce the error when using Koofr. I think I've fixed the problem now. Can you please test again? The link to the prerelease version is the same: https://github.com/sodenn/2do-txt/releases/tag/v1.17.5-json-parse-error.1

**Comment by andreatitolo** [comment]
Confirming that it works perfectly now with Koofr, I have not seen the error at all. Thank you again :)
