### ISSUE TITLE
iOS: Due date tag broken after clicking on recurring task

### ISSUE THREAD

**Issue by jrusnacko** [sodenn/2do-txt#762]
Steps to reproduce the bug:

1. create a recurring task, choose a due date and recurrence first, then add context. App shows something like:
`MyTask rec:+1w Due:03/05/2023 @context`
2. save the task, then click on it. What happens is the following
`MyTask rec:+1w Due:03/12/2023@context`
i.e. the context tag gets mixed up with the incremented due date because the space between them disappears.

This bug is easily circumvented by inputting all context and project tags before the Due date. Still, it seems like a small bug that is easy to fix, so I wanted to let you know.

**Comment by sodenn** [comment]
Hi @jrusnacko, thanks for reporting. I can't reproduce the bug:
![2023-03-07 22 16 47](https://user-images.githubusercontent.com/232054/223557075-92f1ff30-0f8e-44e0-b7b2-15522a85d7ef.gif)
I checked the saved file. The space between due date and context still exists.

**Comment by jrusnacko** [comment]
Hi @sodenn,
I checked again and I might have messed up the description of the bug. It bugs out with the recurrence tag "rec+1w" - after creating the recurring task and clicking on the checkbox near the task the space disappears:

![RPReplay_Final1678227605(1)](https://user-images.githubusercontent.com/52792350/223568729-6577a84a-71eb-4902-acb4-e620779f0810.gif)

Maybe the context tag isn't even playing a role, not sure. Can you reproduce this?

**Comment by sodenn** [comment]
Thank you for the detailed explanation. I can reproduce it now.
