### ISSUE TITLE
Pull to sync in iOS

### ISSUE THREAD

**Issue by apastuszak** [sodenn/2do-txt#776]
The new feature to sync when brought to the foreground is very welcome.  But unfortubnately, it seems that "brought to the foreground" doesn't mean immediately brought to the foreground. The app seems to have to sit in the background for some time (it looks like a minute or longer) before moving it to the foreground will trigger the sync.

I was wondering if we could get a "pull to sync" feature added, where you pull down on the screen to force a sync like many apps have a "pull to  refresh" feature.

**Comment by sodenn** [comment]
Hi @apastuszak. Good idea. Maybe I'll take a look at it in the next few days. FYI: You can already trigger a file sync, but the action is a bit hidden. Go to "Files" => Click on the More button => "Sync wich Dropbox/WebDAV".
