### ISSUE TITLE
Tasks updating every other try on iOS and WebDAV

### ISSUE THREAD

**Issue by frutiking** [sodenn/2do-txt#788]
When I add a new task, or update an existing one while in the iOS app and syncing with a Nextcloud through WebDAV, changes are lost after syncing, and go through on the next try. The cycle repeats upon the next task update.

- Sync'd with a different Nextcloud instance, and the issue persists
- Deleted and re-installed the iOS app, issue continues
- Issue goes away when WebDAV sync is disabled
- I installed and synced to the same WebDAV in the Desktop app, and it's working fine.
- Using version 1.10 of the mobile app

PS:  Keep up the good work!

**Comment by sodenn** [comment]
Good news. I think I have identified the problem. It seems that some WebDAV servers respond with a 204 status code (no content), but also contain a response body, which causes errors on iOS. However, I have an idea how to fix this problem. I will prepare a new iOS release in the next few days.

**Comment by frutiking** [comment]
Great news @sodenn! Thanks for the quick resolution!
