### ISSUE TITLE
Docker Version

### ISSUE THREAD

**Issue by uGeek** [sodenn/2do-txt#873]
It would be possible to create a version for docker as a service with AMR64 and AMD64 architectures.

It would be awesome to have it as a service and access it from different devices.

**Comment by sodenn** [comment]
Hi @uGeek, thanks for the feature request. What is the benefit of having a docker version? The todo.txt files are stored on the local device when using the web version (https://2do-txt-sodenn.vercel.app contains the latest development version). Have you tried the desktop and mobile app? It allows you to sync your todo.txt files between devices by using Dropbox or WebDAV.
