### ISSUE TITLE
Clear all Filters

### ISSUE THREAD

**Issue by jtmusky** [sodenn/2do-txt#880]
Feature request - Would like the ability to reset all filters with a single button.

Thank you for considering
-JM

**Comment by sodenn** [comment]
Hi @jtmusky, you can use the `x` shortcut to reset all filters. But I agree that a button would be nice, especially for mobile users.

**Comment by jtmusky** [comment]
I didn't see an X on the iPhone version. So yes please.

I tried to run the desktop version to verify if that is the x you mentioned, but it fails to load because glibc on rhel9 is less then the minimum from the available precompiled releases. 

-JM
